/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adcs_project;

/**
 *
 * @author Charles
 */

import java.awt.image.BufferedImage;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class BiometricUpdate extends javax.swing.JDialog {
   private  String pix="";
   private Reconsoft rs=new Reconsoft();
 // private Reconsoft2 data=new Reconsoft2();
   private  BiometricSet1  bio;

   private  String sig="";
   private String student_staff_id="";
   private String bioinfo[]=BiometricMain.getDB_Biodata();
    /**
     * Creates new form StudentInfor
     */
    public BiometricUpdate(String reg) {
        bio= rs.RetriveImage(reg);
        student_staff_id=reg;
        initComponents();
        
        pixL.setIcon(new ImageIcon( bio.getBufferedPix()));
        sigL.setIcon(new ImageIcon( bio.getBufferedSig()));
        finL.setIcon(new ImageIcon( bio.getBufferedFingerPrint()));
        
        
    }
    public byte [] convertPixtobyte(BufferedImage m)
   {
      // byte [] pixbyte= new byte[5000];
       //int byteread=0;
      // ByteArrayOutputStream pixout = new ByteArrayOutputStream();
       
     try{
       ByteArrayOutputStream pixout = new ByteArrayOutputStream();
    ImageIO.write(m,"png", pixout);
    byte [] pixbyte=pixout.toByteArray();
  //ByteArrayInputStream  pix =new ByteArrayInputStream(pixout.toByteArray(),0,pixout.size()); 
  return pixbyte;
       }catch(IOException n){
           n.printStackTrace();
           return null;
       }
       
   }
    public void UpdatePicture(){
        
      //  ImageCapturing b = new ImageCapturing();
         if(ImageCapturing.getBufferedImage()!=null)
        {
            rs.UpdateBiometricImageInfor(2,"picture_img", student_staff_id,convertPixtobyte(ImageCapturing.getBufferedImage()));
          //  data.UpdateBiometricImageInfor(2,"picture_img", student_staff_id,convertPixtobyte(ImageCapturing.getBufferedImage()));
           
            JOptionPane.showMessageDialog(this,"Your Picture was updated successfully", "SUCCESSFUL BIOMETRIC DATA UPDATE", 2);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Your Picture was  NOT updated successfully", "UNSUCCESSFUL BIOMETRIC DATA UPDATE", 2);
        }
        
    }
    public void UpdateSignature(){
        
        if(SigPlusImg.getBufferedImage()!=null)
        {
            rs.UpdateBiometricImageInfor(3,"sign_img", student_staff_id,convertPixtobyte(SigPlusImg.getBufferedImage()));
          //  data.UpdateBiometricImageInfor(3,"sign_img", student_staff_id,convertPixtobyte(SigPlusImg.getBufferedImage()));
          
            JOptionPane.showMessageDialog(this,"Your Signature was updated successfully", "SUCCESSFUL BIOMETRIC DATA UPDATE", 2);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Your Signature was  NOT updated successfully", "UNSUCCESSFUL BIOMETRIC DATA UPDATE", 2);
        }
    }
    public void UpdateFingerPrint(){
        //BiometricMain.FingerPrint();
        if(AfamFP.getBufferedImage()!=null)
        {
            rs.UpdateBiometricImageInfor(4,"finger_img", student_staff_id,convertPixtobyte(AfamFP.getBufferedImage()));
         //   data.UpdateBiometricImageInfor(4,"finger_img", student_staff_id,convertPixtobyte(AfamFP.getBufferedImage()));
           
            JOptionPane.showMessageDialog(this,"Your FingerPrint was updated successfully", "SUCCESSFUL BIOMETRIC DATA UPDATE", 2);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Your FingerPrint was  NOT updated successfully", "UNSUCCESSFUL BIOMETRIC DATA UPDATE", 2);
        }
         
        
    }
        
 
    public void AddStudentsBiometricInfo()
    {
        Reconsoft rs=new Reconsoft();
       
       
       
        
        rs.AddStudentBiometricInfor(bioinfo[2], pix, sig, "myFp.jpg");
        
        javax.swing.JOptionPane.showMessageDialog(this,"Insertion Successful");
    }
    public void ClearInputs()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pixL = new javax.swing.JLabel();
        sigL = new javax.swing.JLabel();
        finL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pixB = new javax.swing.JButton();
        sigB = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        finB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biometric Information");

        ContentPane.setBackground(new java.awt.Color(153, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Picture");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("FingerPrint");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Signature");

        pixL.setIcon(new javax.swing.ImageIcon(bio.getBufferedPix()));

        sigL.setIcon(new javax.swing.ImageIcon(bio.getBufferedSig()));

        finL.setIcon(new javax.swing.ImageIcon(bio.getBufferedFingerPrint()));

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pixB.setText("Update");
        pixB.setEnabled(false);
        pixB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixBActionPerformed(evt);
            }
        });

        sigB.setText("Update");
        sigB.setEnabled(false);
        sigB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigBActionPerformed(evt);
            }
        });

        jButton4.setText("Change");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Change");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        finB.setText("Update");
        finB.setEnabled(false);
        finB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentPaneLayout = new javax.swing.GroupLayout(ContentPane);
        ContentPane.setLayout(ContentPaneLayout);
        ContentPaneLayout.setHorizontalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sigL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(finL, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pixL, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ContentPaneLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jButton4)
                            .addGap(26, 26, 26)
                            .addComponent(sigB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContentPaneLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(pixB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        ContentPaneLayout.setVerticalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pixL, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(pixB))))
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(sigL, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sigB)
                            .addComponent(jButton4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel6))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(finL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(finB))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sigBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigBActionPerformed
        // TODO add your handling code here:
        this.UpdateSignature();
    }//GEN-LAST:event_sigBActionPerformed

    private void finBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finBActionPerformed
        // TODO add your handling code here:
        this.UpdateFingerPrint();
    }//GEN-LAST:event_finBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ImageCapturing b = new ImageCapturing();
        pixB.setEnabled(true);
        if(ImageCapturing.getBufferedImage()!=null)
        {
            //System.out.println("The update pix is here"+ImageCapturing.getBufferedImage().toString());
       // pixL.setIcon(new ImageIcon(ImageCapturing.getBufferedImage()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        BiometricMain.SignaturePage();
        sigB.setEnabled(true);
        if(SigPlusImg.getBufferedImage()!=null)
        {
            
            //System.out.println("The update sig is here"+SigPlusImg.getBufferedImage().toString());
        
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        BiometricMain.FingerPrint();
        finB.setEnabled(true);
        if(AfamFP.getBufferedImage()!=null){
            System.out.println("The update fig is here"+AfamFP.getBufferedImage().toString());
            
        
        //finL.setIcon(new ImageIcon(AfamFP.getBufferedImage()));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pixBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixBActionPerformed
        // TODO add your handling code here:
        this.UpdatePicture();
    }//GEN-LAST:event_pixBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String [] args)
    {
        new BiometricUpdate("SP 111").setVisible(true);
        //Reconsoft rs=new Reconsoft();




        //rs.AddStudentBiometricInfor("2006/419419", "pix.jpg", "sig.jpg", "myFp.jpg");

       //System.out.println("Insertion Successful");
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPane;
    private javax.swing.JButton finB;
    public static javax.swing.JLabel finL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pixB;
    public static javax.swing.JLabel pixL;
    private javax.swing.JButton sigB;
    public static javax.swing.JLabel sigL;
    // End of variables declaration//GEN-END:variables
}
